apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookapp-external-secret
spec:
  refreshInterval: "15s"  # Added refresh interval
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: bookapp-env-secret
    creationPolicy: Owner  # Added creation policy
    template:
      engineVersion: v2  # Added engine version
      data:
        .env: |
          POSTGRES_USER={{ "{{" }}.rds_username{{ "}}" }}
          POSTGRES_PASSWORD={{ "{{" }}.rds_password{{ "}}" }}
          POSTGRES_DB={{ "{{" }}.rds_db_name{{ "}}" }}
          POSTGRES_HOST={{ "{{" }}.rds_endpoint{{ "}}" }}
          DATABASE_URL=postgresql://{{ "{{" }}.rds_username{{ "}}" }}:{{ "{{" }}.rds_password{{ "}}" }}@{{ "{{" }}.rds_endpoint{{ "}}" }}/{{ "{{" }}.rds_db_name{{ "}}" }}
          POSTGRES_PORT=5432
          REDIS_HOST={{ "{{" }}.redis_host{{ "}}" }}
          RABBITMQ_HOST={{ "{{" }}.rabbitmq_host{{ "}}" }}
          RABBITMQ_USERNAME={{ "{{" }}.rabbitmq_username{{ "}}" }}
          RABBITMQ_PASSWORD={{ "{{" }}.rabbitmq_password{{ "}}" }}
  data:
    - secretKey: rds_username
      remoteRef:
        key: /dev/rds/username
        version: "1"  # Added version specification
    - secretKey: rds_password
      remoteRef:
        key: /dev/rds/password
        version: "1"
    - secretKey: rds_db_name
      remoteRef:
        key: /dev/rds/db_name
        version: "1"
    - secretKey: rds_endpoint
      remoteRef:
        key: /dev/rds/endpoint
        version: "1"
    - secretKey: redis_host
      remoteRef:
        key: /dev/redis/endpoint
        version: "1"
    - secretKey: rabbitmq_host
      remoteRef:
        key: /dev/rabbitmq/endpoint
        version: "1"
    - secretKey: rabbitmq_username
      remoteRef:
        key: /dev/rabbitmq/username
        version: "1"
    - secretKey: rabbitmq_password
      remoteRef:
        key: /dev/rabbitmq/password
        version: "1"
