apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookapp-external-secret
spec:
  refreshInterval: "15s"  # Added refresh interval
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: bookapp-secret
    creationPolicy: Owner  # Added creation policy
    template:
      engineVersion: v2
      data:
        .env: |-
          POSTGRES_USER="{{`{{ .secret.data.rds_username }}`}}"
          POSTGRES_PASSWORD="{{`{{ .secret.data.rds_password }}`}}"
          POSTGRES_DB="{{`{{ .secret.data.rds_db_name }}`}}"
          POSTGRES_HOST="{{`{{ .secret.data.rds_endpoint }}`}}"
          DATABASE_URL="postgresql://{{`{{ .secret.data.rds_username }}`}}:{{`{{ .secret.data.rds_password }}`}}@{{`{{ .secret.data.rds_endpoint }}`}}/{{`{{ .secret.data.rds_db_name }}`}}"
          POSTGRES_PORT=5432
          REDIS_HOST="{{`{{ .secret.data.redis_host }}`}}"
          RABBITMQ_HOST="{{`{{ .secret.data.rabbitmq_host }}`}}"
          RABBITMQ_USERNAME="{{`{{ .secret.data.rabbitmq_username }}`}}"
          RABBITMQ_PASSWORD="{{`{{ .secret.data.rabbitmq_password }}`}}"
  data:
    - secretKey: rds_username
      remoteRef:
        key: /dev/rds/username
    - secretKey: rds_password
      remoteRef:
        key: /dev/rds/password
    - secretKey: rds_db_name
      remoteRef:
        key: /dev/rds/db_name
    - secretKey: rds_endpoint
      remoteRef:
        key: /dev/rds/endpoint
    - secretKey: redis_host
      remoteRef:
        key: /dev/redis/endpoint
    - secretKey: rabbitmq_host
      remoteRef:
        key: /dev/rabbitmq/endpoint
    - secretKey: rabbitmq_username
      remoteRef:
        key: /dev/rabbitmq/username
    - secretKey: rabbitmq_password
      remoteRef:
        key: /dev/rabbitmq/password
