apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookapp-secret
spec:
  refreshInterval: "15s"  # Added refresh interval
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: bookapp-secret
    creationPolicy: Owner  # Added creation policy
  data:
    - secretKey: rds_username
      remoteRef:
        key: /dev/rds/username
        version: "1"  # Added version specification
    - secretKey: rds_password
      remoteRef:
        key: /dev/rds/password
        version: "1"
    - secretKey: rds_db_name
      remoteRef:
        key: /dev/rds/db_name
        version: "1"
    - secretKey: rds_endpoint
      remoteRef:
        key: /dev/rds/endpoint
        version: "1"
    - secretKey: redis_host
      remoteRef:
        key: /dev/redis/endpoint
        version: "1"
    - secretKey: rabbitmq_host
      remoteRef:
        key: /dev/rabbitmq/endpoint
        version: "1"
    - secretKey: rabbitmq_username
      remoteRef:
        key: /dev/rabbitmq/username
        version: "1"
    - secretKey: rabbitmq_password
      remoteRef:
        key: /dev/rabbitmq/password
        version: "1"
