apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args: ["export SECRET_KEY=$(openssl rand -hex 32) && alembic upgrade head && uvicorn auth.main:app --host 0.0.0.0 --port 8002 --reload"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: rds_connection_string
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: rds_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: rds_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: rds_db_name
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: rds_endpoint
            - name: POSTGRES_PORT
              value: "5432"
            # - name: SECRET_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: bookapp-secret
            #       key: secret_key
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: redis_host
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: rabbitmq_host  
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: rabbitmq_username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookapp-secret
                  key: rabbitmq_password

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: bookapp-secret
            mountPath: /code/.env
            subPath: .env
      volumes:
      - name: bookapp-secret
        secret:
          secretName: bookapp-secret
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
