apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order.fullname" . }}
  labels:
    {{- include "order.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "order.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "order.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "order.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["/bin/bash", "-c"]
          # args: ["export SECRET_KEY=$(openssl rand -hex 32) && alembic upgrade head && uvicorn order.main:app --host 0.0.0.0 --port 8001 --reload"]
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: bookapp-secret
                key: rds_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bookapp-secret
                key: rds_password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: bookapp-secret
                key: rds_db_name
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: bookapp-secret
                key: rds_endpoint
          - name: POSTGRES_PORT
            value: {{ .Values.postgresql.port | quote }}
          - name: DATABASE_URL
            value: "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: bookapp-secret
                key: redis_host
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: bookapp-secret
                key: rabbitmq_host
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: bookapp-secret
            mountPath: /code/.env
            subPath: .env
      volumes:
      - name: bookapp-secret
        secret:
          secretName: bookapp-secret
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
