# Specific settings for each sub-chart
tntk-web:
  fullnameOverride: "tntk-web-dev"
  replicaCount: 1
  image:
    repository: "038891198925.dkr.ecr.us-east-2.amazonaws.com/dev/tntk-web"
    pullPolicy: IfNotPresent
    tag: ""
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 80
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  configmapData:
    PORT: "80"
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: "tntk-bookapp.ernestdevops.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
tntk-orders:
  fullnameOverride: "tntk-orders-dev"
  replicaCount: 1
  image:
    repository: "038891198925.dkr.ecr.us-east-2.amazonaws.com/dev/tntk-orders"
    pullPolicy: IfNotPresent
    tag: "d787f2d7b0edfb61a34109a6fd6da9528d348428"
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 80
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  postgresql:
    host: postgres
    port: 5432
    username: postgres
    password: postgres
    database: postgres
  redis:
    host: redis
  rabbitmq:
    host: rabbitmq
tntk-auth:
  fullnameOverride: "tntk-auth-dev"
  replicaCount: 1
  image:
    repository: "038891198925.dkr.ecr.us-east-2.amazonaws.com/dev/tntk-auth"
    pullPolicy: IfNotPresent
    tag: ""
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 8002
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
tntk-products:
  fullnameOverride: "tntk-products-dev"
  replicaCount: 1
  image:
    repository: "038891198925.dkr.ecr.us-east-2.amazonaws.com/dev/tntk-products"
    pullPolicy: IfNotPresent
    tag: "ff8ef356c0e5ff9c71b34ab868d3e978a47272cc"
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
shared-resources:
  fullnameOverride: "shared-resources"
  replicaCount: 1
  aws:
    region: us-east-2
  global:
    nodeSelector: {}
    tolerations: []
    affinity: {}
    service:
      port: 80
  ingress:
    enabled: true
    className: "alb"
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": "80"}, {"HTTPS": "443"}]' # Ensure ports are strings
      alb.ingress.kubernetes.io/ssl-redirect: "443" # Ensure this is a string
      # Add other annotations as needed
      # nginx.ingress.kubernetes.io/rewrite-target: /
      # kubernetes.io/tls-acme: "true"
    # TLS configuration
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

    # Ingress hosts configuration
    hosts:
      - host: "argocd.test.com"
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
